### ISSUE TITLE
Imgur image posting error 400?

### ISSUE THREAD

**Issue by RikerW** [The-Quill/SE-Chat-Oneboxer#38] opened 2016-06-06 23:32 UTC
At random times Chrome on OS X will alert me `Error posting old image to imgur. Server status 400`.

I don't see any repercussions of this. But the error could stop?

**Comment by The-Quill** [comment] 2016-06-07 00:21
@RikerW what chrome version are you using and can you screenshot this?

**Comment by RikerW** [comment] 2016-06-07 03:17
Chrome 50.  Traceback:

http://i.stack.imgur.com/kJPAo.png

I'll screenshot the alert next time I see it.

**Comment by RikerW** [comment] 2016-06-08 20:16
http://imgur.com/VBmHJTT

**Comment by The-Quill** [comment] 2016-06-08 21:57
I think this is a config issue.... I need to do some better error handling though

**Comment by RikerW** [comment] 2016-07-09 15:39
@The-Quill hows it going? >_>

**Comment by RikerW** [comment] 2016-07-23 21:22
@The-Quill  how's it going now? >_>

**Comment by The-Quill** [comment] 2016-07-23 22:20
This issue feels like an update issue, and considering I never actully use any image uploading code, I'm gonna close this as no-repro

**Closed by The-Quill** 2016-07-23 22:20 UTC
Labels: bug

**Comment by vihanb** [comment] 2016-07-23 23:18
@The-Quill if you don't want to fix it you can always post this image:

https://camo.githubusercontent.com/d58c5fc5c80f05d4d4d7ada765b4786a9b77c812/687474703a2f2f692e696d67666c69702e636f6d2f31306f3034322e6a7067

**Comment by The-Quill** [comment] 2016-07-23 23:19
@vihanb It's not that I don't want to fix it, I just generally can't fix it, or I can't reproduce it enough to fix it myelf
